
# tools we expect devs across many scenarios will want
choco install -y vscode
choco install -y git -params '"/GitAndUnixToolsOnPath /WindowsTerminal"'
choco install -y python3
choco install -y 7zip.install
choco install -y sysinternals
choco install -y autohotkey
choco install -y awscli
choco install -y beyondcompare
choco install -y bluescreenview
choco install -y cmdermini
choco install -y curl
choco install -y ditto
choco install -y filezilla
choco install -y git
choco install -y gitter
choco install -y golang
choco install -y Gpg4win
choco install -y hyper
choco install -y jfrog-cli
choco install -y JiraCli
choco install -y jq
choco install -y less
choco install -y lua53
choco install -y nodejs
choco install -y packer
choco install -y poshgit
choco install -y postman
choco install -y python3
choco install -y rufus
choco install -y snagit
choco install -y SQLite
choco install -y sqlitebrowser
choco install -y SublimeText3
choco install -y teamviewer
choco install -y terraform
choco install -y vagrant
choco install -y vlc
choco install -y vnc-viewer
choco install -y wget
choco install -y whois
choco install -y wireshark
choco install -y wiztree
choco install -y youtube-dl